with-expecter: true
issue-845-fix: true
disable-version-string: true
resolve-type-alias: false
packages:
  transx/internal/modules/auth/domain/interfaces:
    interfaces:
      UserRepository:
        config:
          dir: internal/testmocks
          outpkg: testmocks
          filename: user_repository.go
          mockname: UserRepository
      RefreshSessionStore:
        config:
          dir: internal/testmocks
          outpkg: testmocks
          filename: refresh_session_store.go
          mockname: RefreshSessionStore
      TokenService:
        config:
          dir: internal/testmocks
          outpkg: testmocks
          filename: token_service.go
          mockname: TokenService
  transx/internal/modules/wallet/domain/interfaces:
    interfaces:
      AccountRepository:
        config:
          dir: internal/testmocks
          outpkg: testmocks
          filename: account_repository.go
          mockname: AccountRepository
      MoneyRepository:
        config:
          dir: internal/testmocks
          outpkg: testmocks
          filename: money_repository.go
          mockname: MoneyRepository
  transx/internal/modules/transfer/domain/interfaces:
    interfaces:
      TransferRepository:
        config:
          dir: internal/testmocks
          outpkg: testmocks
          filename: transfer_repository.go
          mockname: TransferRepository
      InboxRepository:
        config:
          dir: internal/testmocks
          outpkg: testmocks
          filename: inbox_repository.go
          mockname: InboxRepository
      ProviderClient:
        config:
          dir: internal/testmocks
          outpkg: testmocks
          filename: provider_client.go
          mockname: ProviderClient
