package cli

import (
	"context"
	"fmt"

	"github.com/urfave/cli/v2"
	"golang.org/x/crypto/bcrypt"

	"transx/internal/platform/config"
	"transx/internal/platform/postgres"
)

// seedUser describes a development user inserted by the seed command. IDs are
// generated by the database (uuidv7() default), so none is specified here.
type seedUser struct {
	Email    string
	Password string
	Name     string
}

// devUsers are the fixed development accounts. Passwords are hashed at runtime
// so the plaintext stays visible here for local testing (login + ForwardAuth).
var devUsers = []seedUser{
	{Email: "alice@transx.dev", Password: "password123", Name: "Alice"},
	{Email: "bob@transx.dev", Password: "password123", Name: "Bob"},
	{Email: "carol@transx.dev", Password: "password123", Name: "Carol"},
	{Email: "dave@transx.dev", Password: "password123", Name: "Dave"},
	{Email: "eve@transx.dev", Password: "password123", Name: "Eve"},
}

// Seed inserts the development users. It is idempotent: re-running refreshes the
// password hash and name for existing emails rather than failing. The user id is
// assigned by the database default (uuidv7()).
func Seed(c *cli.Context) error {
	ctx := context.Background()

	cfg, err := config.Load(c.String("config"))
	if err != nil {
		return err
	}

	db, err := postgres.Connect(ctx, cfg.Postgres)
	if err != nil {
		return err
	}
	defer db.Close()

	for _, u := range devUsers {
		hash, err := bcrypt.GenerateFromPassword([]byte(u.Password), bcrypt.DefaultCost)
		if err != nil {
			return fmt.Errorf("seed: hash password for %s: %w", u.Email, err)
		}

		_, err = db.Exec(ctx, `
			INSERT INTO users (email, password_hash, name)
			VALUES ($1, $2, $3)
			ON CONFLICT (email) DO UPDATE
			SET password_hash = EXCLUDED.password_hash,
			    name          = EXCLUDED.name,
			    updated_at    = now()`,
			u.Email, string(hash), u.Name,
		)
		if err != nil {
			return fmt.Errorf("seed: upsert user %s: %w", u.Email, err)
		}

		fmt.Printf("seeded user %s (%s)\n", u.Email, u.Password)
	}

	if err := seedAccounts(ctx, db); err != nil {
		return err
	}

	fmt.Printf("Seeded %d user(s) successfully\n", len(devUsers))
	return nil
}

// seedAccount describes a development wallet account. The id is assigned by the
// database (uuidv7() default); user_id is resolved from the owner's email.
type seedAccount struct {
	OwnerEmail string
	Name       string
	Currency   string
	Balance    string
}

// devAccounts are fixed development wallets used to exercise transfers.
var devAccounts = []seedAccount{
	{OwnerEmail: "alice@transx.dev", Name: "alice-main", Currency: "USD", Balance: "1000.0000"},
	{OwnerEmail: "bob@transx.dev", Name: "bob-main", Currency: "USD", Balance: "500.0000"},
}

// seedAccounts upserts the development wallet accounts. It is idempotent via
// ON CONFLICT (user_id, name); the balance/currency are refreshed on re-run.
func seedAccounts(ctx context.Context, db *postgres.Pool) error {
	for _, a := range devAccounts {
		_, err := db.Exec(ctx, `
			INSERT INTO accounts (user_id, name, currency, available_balance, status)
			SELECT u.id, $2, $3, $4, 'ACTIVE'
			FROM users u
			WHERE u.email = $1
			ON CONFLICT (user_id, name) DO UPDATE
			SET currency          = EXCLUDED.currency,
			    available_balance = EXCLUDED.available_balance,
			    updated_at        = now()`,
			a.OwnerEmail, a.Name, a.Currency, a.Balance,
		)
		if err != nil {
			return fmt.Errorf("seed: upsert account %s/%s: %w", a.OwnerEmail, a.Name, err)
		}
		fmt.Printf("seeded account %s for %s (%s %s)\n", a.Name, a.OwnerEmail, a.Balance, a.Currency)
	}
	return nil
}
