// Code generated by mockery. DO NOT EDIT.

package testmocks

import (
	context "context"
	entities "transx/internal/modules/wallet/domain/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

type AccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountRepository) EXPECT() *AccountRepository_Expecter {
	return &AccountRepository_Expecter{mock: &_m.Mock}
}

// CountByUser provides a mock function with given fields: ctx, userID, currency, status
func (_m *AccountRepository) CountByUser(ctx context.Context, userID uuid.UUID, currency *string, status *string) (int64, error) {
	ret := _m.Called(ctx, userID, currency, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string) (int64, error)); ok {
		return rf(ctx, userID, currency, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string) int64); ok {
		r0 = rf(ctx, userID, currency, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, *string) error); ok {
		r1 = rf(ctx, userID, currency, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_CountByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUser'
type AccountRepository_CountByUser_Call struct {
	*mock.Call
}

// CountByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currency *string
//   - status *string
func (_e *AccountRepository_Expecter) CountByUser(ctx interface{}, userID interface{}, currency interface{}, status interface{}) *AccountRepository_CountByUser_Call {
	return &AccountRepository_CountByUser_Call{Call: _e.mock.On("CountByUser", ctx, userID, currency, status)}
}

func (_c *AccountRepository_CountByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, currency *string, status *string)) *AccountRepository_CountByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *AccountRepository_CountByUser_Call) Return(_a0 int64, _a1 error) *AccountRepository_CountByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_CountByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, *string, *string) (int64, error)) *AccountRepository_CountByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, a
func (_m *AccountRepository) Create(ctx context.Context, a *entities.Account) (*entities.Account, error) {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Account) (*entities.Account, error)); ok {
		return rf(ctx, a)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Account) *entities.Account); ok {
		r0 = rf(ctx, a)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Account) error); ok {
		r1 = rf(ctx, a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entities.Account
func (_e *AccountRepository_Expecter) Create(ctx interface{}, a interface{}) *AccountRepository_Create_Call {
	return &AccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *AccountRepository_Create_Call) Run(run func(ctx context.Context, a *entities.Account)) *AccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Account))
	})
	return _c
}

func (_c *AccountRepository_Create_Call) Return(_a0 *entities.Account, _a1 error) *AccountRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.Account) (*entities.Account, error)) *AccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AccountRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AccountRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AccountRepository_Expecter) GetByID(ctx interface{}, id interface{}) *AccountRepository_GetByID_Call {
	return &AccountRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *AccountRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AccountRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AccountRepository_GetByID_Call) Return(_a0 *entities.Account, _a1 error) *AccountRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entities.Account, error)) *AccountRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByRef provides a mock function with given fields: ctx, ref
func (_m *AccountRepository) GetByRef(ctx context.Context, ref string) (*entities.Account, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetByRef")
	}

	var r0 *entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Account, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Account); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_GetByRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRef'
type AccountRepository_GetByRef_Call struct {
	*mock.Call
}

// GetByRef is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *AccountRepository_Expecter) GetByRef(ctx interface{}, ref interface{}) *AccountRepository_GetByRef_Call {
	return &AccountRepository_GetByRef_Call{Call: _e.mock.On("GetByRef", ctx, ref)}
}

func (_c *AccountRepository_GetByRef_Call) Run(run func(ctx context.Context, ref string)) *AccountRepository_GetByRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountRepository_GetByRef_Call) Return(_a0 *entities.Account, _a1 error) *AccountRepository_GetByRef_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_GetByRef_Call) RunAndReturn(run func(context.Context, string) (*entities.Account, error)) *AccountRepository_GetByRef_Call {
	_c.Call.Return(run)
	return _c
}

// GetByRefForUser provides a mock function with given fields: ctx, ref, userID
func (_m *AccountRepository) GetByRefForUser(ctx context.Context, ref string, userID uuid.UUID) (*entities.Account, error) {
	ret := _m.Called(ctx, ref, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByRefForUser")
	}

	var r0 *entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*entities.Account, error)); ok {
		return rf(ctx, ref, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *entities.Account); ok {
		r0 = rf(ctx, ref, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, ref, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_GetByRefForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRefForUser'
type AccountRepository_GetByRefForUser_Call struct {
	*mock.Call
}

// GetByRefForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - userID uuid.UUID
func (_e *AccountRepository_Expecter) GetByRefForUser(ctx interface{}, ref interface{}, userID interface{}) *AccountRepository_GetByRefForUser_Call {
	return &AccountRepository_GetByRefForUser_Call{Call: _e.mock.On("GetByRefForUser", ctx, ref, userID)}
}

func (_c *AccountRepository_GetByRefForUser_Call) Run(run func(ctx context.Context, ref string, userID uuid.UUID)) *AccountRepository_GetByRefForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AccountRepository_GetByRefForUser_Call) Return(_a0 *entities.Account, _a1 error) *AccountRepository_GetByRefForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_GetByRefForUser_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) (*entities.Account, error)) *AccountRepository_GetByRefForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetLookupByRef provides a mock function with given fields: ctx, ref
func (_m *AccountRepository) GetLookupByRef(ctx context.Context, ref string) (*entities.AccountLookup, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetLookupByRef")
	}

	var r0 *entities.AccountLookup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.AccountLookup, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.AccountLookup); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AccountLookup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_GetLookupByRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLookupByRef'
type AccountRepository_GetLookupByRef_Call struct {
	*mock.Call
}

// GetLookupByRef is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *AccountRepository_Expecter) GetLookupByRef(ctx interface{}, ref interface{}) *AccountRepository_GetLookupByRef_Call {
	return &AccountRepository_GetLookupByRef_Call{Call: _e.mock.On("GetLookupByRef", ctx, ref)}
}

func (_c *AccountRepository_GetLookupByRef_Call) Run(run func(ctx context.Context, ref string)) *AccountRepository_GetLookupByRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountRepository_GetLookupByRef_Call) Return(_a0 *entities.AccountLookup, _a1 error) *AccountRepository_GetLookupByRef_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_GetLookupByRef_Call) RunAndReturn(run func(context.Context, string) (*entities.AccountLookup, error)) *AccountRepository_GetLookupByRef_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, currency, status, limit, offset
func (_m *AccountRepository) ListByUser(ctx context.Context, userID uuid.UUID, currency *string, status *string, limit int32, offset int32) ([]*entities.Account, error) {
	ret := _m.Called(ctx, userID, currency, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, int32, int32) ([]*entities.Account, error)); ok {
		return rf(ctx, userID, currency, status, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, int32, int32) []*entities.Account); ok {
		r0 = rf(ctx, userID, currency, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, *string, int32, int32) error); ok {
		r1 = rf(ctx, userID, currency, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type AccountRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currency *string
//   - status *string
//   - limit int32
//   - offset int32
func (_e *AccountRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, currency interface{}, status interface{}, limit interface{}, offset interface{}) *AccountRepository_ListByUser_Call {
	return &AccountRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, currency, status, limit, offset)}
}

func (_c *AccountRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, currency *string, status *string, limit int32, offset int32)) *AccountRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*string), args[3].(*string), args[4].(int32), args[5].(int32))
	})
	return _c
}

func (_c *AccountRepository_ListByUser_Call) Return(_a0 []*entities.Account, _a1 error) *AccountRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, *string, *string, int32, int32) ([]*entities.Account, error)) *AccountRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
