// Code generated by mockery. DO NOT EDIT.

package testmocks

import (
	context "context"
	entities "transx/internal/modules/wallet/domain/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

type AccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountRepository) EXPECT() *AccountRepository_Expecter {
	return &AccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *AccountRepository) Create(ctx context.Context, a *entities.Account) (*entities.Account, error) {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Account) (*entities.Account, error)); ok {
		return rf(ctx, a)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Account) *entities.Account); ok {
		r0 = rf(ctx, a)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Account) error); ok {
		r1 = rf(ctx, a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entities.Account
func (_e *AccountRepository_Expecter) Create(ctx interface{}, a interface{}) *AccountRepository_Create_Call {
	return &AccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *AccountRepository_Create_Call) Run(run func(ctx context.Context, a *entities.Account)) *AccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Account))
	})
	return _c
}

func (_c *AccountRepository_Create_Call) Return(_a0 *entities.Account, _a1 error) *AccountRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.Account) (*entities.Account, error)) *AccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AccountRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AccountRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AccountRepository_Expecter) GetByID(ctx interface{}, id interface{}) *AccountRepository_GetByID_Call {
	return &AccountRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *AccountRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AccountRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AccountRepository_GetByID_Call) Return(_a0 *entities.Account, _a1 error) *AccountRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entities.Account, error)) *AccountRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDForUser provides a mock function with given fields: ctx, id, userID
func (_m *AccountRepository) GetByIDForUser(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entities.Account, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDForUser")
	}

	var r0 *entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entities.Account, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entities.Account); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_GetByIDForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDForUser'
type AccountRepository_GetByIDForUser_Call struct {
	*mock.Call
}

// GetByIDForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *AccountRepository_Expecter) GetByIDForUser(ctx interface{}, id interface{}, userID interface{}) *AccountRepository_GetByIDForUser_Call {
	return &AccountRepository_GetByIDForUser_Call{Call: _e.mock.On("GetByIDForUser", ctx, id, userID)}
}

func (_c *AccountRepository_GetByIDForUser_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *AccountRepository_GetByIDForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AccountRepository_GetByIDForUser_Call) Return(_a0 *entities.Account, _a1 error) *AccountRepository_GetByIDForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_GetByIDForUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entities.Account, error)) *AccountRepository_GetByIDForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
