// Code generated by mockery. DO NOT EDIT.

package testmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// InboxRepository is an autogenerated mock type for the InboxRepository type
type InboxRepository struct {
	mock.Mock
}

type InboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InboxRepository) EXPECT() *InboxRepository_Expecter {
	return &InboxRepository_Expecter{mock: &_m.Mock}
}

// IsProcessed provides a mock function with given fields: ctx, group, messageKey
func (_m *InboxRepository) IsProcessed(ctx context.Context, group string, messageKey string) (bool, error) {
	ret := _m.Called(ctx, group, messageKey)

	if len(ret) == 0 {
		panic("no return value specified for IsProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, group, messageKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, group, messageKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, group, messageKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InboxRepository_IsProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsProcessed'
type InboxRepository_IsProcessed_Call struct {
	*mock.Call
}

// IsProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - group string
//   - messageKey string
func (_e *InboxRepository_Expecter) IsProcessed(ctx interface{}, group interface{}, messageKey interface{}) *InboxRepository_IsProcessed_Call {
	return &InboxRepository_IsProcessed_Call{Call: _e.mock.On("IsProcessed", ctx, group, messageKey)}
}

func (_c *InboxRepository_IsProcessed_Call) Run(run func(ctx context.Context, group string, messageKey string)) *InboxRepository_IsProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *InboxRepository_IsProcessed_Call) Return(_a0 bool, _a1 error) *InboxRepository_IsProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InboxRepository_IsProcessed_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *InboxRepository_IsProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function with given fields: ctx, group, messageKey
func (_m *InboxRepository) MarkProcessed(ctx context.Context, group string, messageKey string) error {
	ret := _m.Called(ctx, group, messageKey)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, group, messageKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InboxRepository_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type InboxRepository_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - group string
//   - messageKey string
func (_e *InboxRepository_Expecter) MarkProcessed(ctx interface{}, group interface{}, messageKey interface{}) *InboxRepository_MarkProcessed_Call {
	return &InboxRepository_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, group, messageKey)}
}

func (_c *InboxRepository_MarkProcessed_Call) Run(run func(ctx context.Context, group string, messageKey string)) *InboxRepository_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *InboxRepository_MarkProcessed_Call) Return(_a0 error) *InboxRepository_MarkProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InboxRepository_MarkProcessed_Call) RunAndReturn(run func(context.Context, string, string) error) *InboxRepository_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// NewInboxRepository creates a new instance of InboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InboxRepository {
	mock := &InboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
