// Code generated by mockery. DO NOT EDIT.

package testmocks

import (
	context "context"
	interfaces "transx/internal/modules/wallet/domain/interfaces"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MoneyRepository is an autogenerated mock type for the MoneyRepository type
type MoneyRepository struct {
	mock.Mock
}

type MoneyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MoneyRepository) EXPECT() *MoneyRepository_Expecter {
	return &MoneyRepository_Expecter{mock: &_m.Mock}
}

// Hold provides a mock function with given fields: ctx, transferID, operation, accountRef, amount, currency
func (_m *MoneyRepository) Hold(ctx context.Context, transferID uuid.UUID, operation string, accountRef string, amount decimal.Decimal, currency string) (interfaces.HoldResult, error) {
	ret := _m.Called(ctx, transferID, operation, accountRef, amount, currency)

	if len(ret) == 0 {
		panic("no return value specified for Hold")
	}

	var r0 interfaces.HoldResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) (interfaces.HoldResult, error)); ok {
		return rf(ctx, transferID, operation, accountRef, amount, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) interfaces.HoldResult); ok {
		r0 = rf(ctx, transferID, operation, accountRef, amount, currency)
	} else {
		r0 = ret.Get(0).(interfaces.HoldResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) error); ok {
		r1 = rf(ctx, transferID, operation, accountRef, amount, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoneyRepository_Hold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hold'
type MoneyRepository_Hold_Call struct {
	*mock.Call
}

// Hold is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID uuid.UUID
//   - operation string
//   - accountRef string
//   - amount decimal.Decimal
//   - currency string
func (_e *MoneyRepository_Expecter) Hold(ctx interface{}, transferID interface{}, operation interface{}, accountRef interface{}, amount interface{}, currency interface{}) *MoneyRepository_Hold_Call {
	return &MoneyRepository_Hold_Call{Call: _e.mock.On("Hold", ctx, transferID, operation, accountRef, amount, currency)}
}

func (_c *MoneyRepository_Hold_Call) Run(run func(ctx context.Context, transferID uuid.UUID, operation string, accountRef string, amount decimal.Decimal, currency string)) *MoneyRepository_Hold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(decimal.Decimal), args[5].(string))
	})
	return _c
}

func (_c *MoneyRepository_Hold_Call) Return(_a0 interfaces.HoldResult, _a1 error) *MoneyRepository_Hold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MoneyRepository_Hold_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) (interfaces.HoldResult, error)) *MoneyRepository_Hold_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function with given fields: ctx, transferID, operation, in
func (_m *MoneyRepository) Move(ctx context.Context, transferID uuid.UUID, operation string, in interfaces.MoveInput) (interfaces.MoveResult, error) {
	ret := _m.Called(ctx, transferID, operation, in)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 interfaces.MoveResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, interfaces.MoveInput) (interfaces.MoveResult, error)); ok {
		return rf(ctx, transferID, operation, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, interfaces.MoveInput) interfaces.MoveResult); ok {
		r0 = rf(ctx, transferID, operation, in)
	} else {
		r0 = ret.Get(0).(interfaces.MoveResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, interfaces.MoveInput) error); ok {
		r1 = rf(ctx, transferID, operation, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoneyRepository_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type MoneyRepository_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID uuid.UUID
//   - operation string
//   - in interfaces.MoveInput
func (_e *MoneyRepository_Expecter) Move(ctx interface{}, transferID interface{}, operation interface{}, in interface{}) *MoneyRepository_Move_Call {
	return &MoneyRepository_Move_Call{Call: _e.mock.On("Move", ctx, transferID, operation, in)}
}

func (_c *MoneyRepository_Move_Call) Run(run func(ctx context.Context, transferID uuid.UUID, operation string, in interfaces.MoveInput)) *MoneyRepository_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(interfaces.MoveInput))
	})
	return _c
}

func (_c *MoneyRepository_Move_Call) Return(_a0 interfaces.MoveResult, _a1 error) *MoneyRepository_Move_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MoneyRepository_Move_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, interfaces.MoveInput) (interfaces.MoveResult, error)) *MoneyRepository_Move_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseHold provides a mock function with given fields: ctx, transferID, operation, accountRef, amount, currency
func (_m *MoneyRepository) ReleaseHold(ctx context.Context, transferID uuid.UUID, operation string, accountRef string, amount decimal.Decimal, currency string) (interfaces.HoldResult, error) {
	ret := _m.Called(ctx, transferID, operation, accountRef, amount, currency)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseHold")
	}

	var r0 interfaces.HoldResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) (interfaces.HoldResult, error)); ok {
		return rf(ctx, transferID, operation, accountRef, amount, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) interfaces.HoldResult); ok {
		r0 = rf(ctx, transferID, operation, accountRef, amount, currency)
	} else {
		r0 = ret.Get(0).(interfaces.HoldResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) error); ok {
		r1 = rf(ctx, transferID, operation, accountRef, amount, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoneyRepository_ReleaseHold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseHold'
type MoneyRepository_ReleaseHold_Call struct {
	*mock.Call
}

// ReleaseHold is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID uuid.UUID
//   - operation string
//   - accountRef string
//   - amount decimal.Decimal
//   - currency string
func (_e *MoneyRepository_Expecter) ReleaseHold(ctx interface{}, transferID interface{}, operation interface{}, accountRef interface{}, amount interface{}, currency interface{}) *MoneyRepository_ReleaseHold_Call {
	return &MoneyRepository_ReleaseHold_Call{Call: _e.mock.On("ReleaseHold", ctx, transferID, operation, accountRef, amount, currency)}
}

func (_c *MoneyRepository_ReleaseHold_Call) Run(run func(ctx context.Context, transferID uuid.UUID, operation string, accountRef string, amount decimal.Decimal, currency string)) *MoneyRepository_ReleaseHold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(decimal.Decimal), args[5].(string))
	})
	return _c
}

func (_c *MoneyRepository_ReleaseHold_Call) Return(_a0 interfaces.HoldResult, _a1 error) *MoneyRepository_ReleaseHold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MoneyRepository_ReleaseHold_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) (interfaces.HoldResult, error)) *MoneyRepository_ReleaseHold_Call {
	_c.Call.Return(run)
	return _c
}

// SettleHold provides a mock function with given fields: ctx, transferID, operation, accountRef, amount, currency
func (_m *MoneyRepository) SettleHold(ctx context.Context, transferID uuid.UUID, operation string, accountRef string, amount decimal.Decimal, currency string) (interfaces.HoldResult, error) {
	ret := _m.Called(ctx, transferID, operation, accountRef, amount, currency)

	if len(ret) == 0 {
		panic("no return value specified for SettleHold")
	}

	var r0 interfaces.HoldResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) (interfaces.HoldResult, error)); ok {
		return rf(ctx, transferID, operation, accountRef, amount, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) interfaces.HoldResult); ok {
		r0 = rf(ctx, transferID, operation, accountRef, amount, currency)
	} else {
		r0 = ret.Get(0).(interfaces.HoldResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) error); ok {
		r1 = rf(ctx, transferID, operation, accountRef, amount, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoneyRepository_SettleHold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SettleHold'
type MoneyRepository_SettleHold_Call struct {
	*mock.Call
}

// SettleHold is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID uuid.UUID
//   - operation string
//   - accountRef string
//   - amount decimal.Decimal
//   - currency string
func (_e *MoneyRepository_Expecter) SettleHold(ctx interface{}, transferID interface{}, operation interface{}, accountRef interface{}, amount interface{}, currency interface{}) *MoneyRepository_SettleHold_Call {
	return &MoneyRepository_SettleHold_Call{Call: _e.mock.On("SettleHold", ctx, transferID, operation, accountRef, amount, currency)}
}

func (_c *MoneyRepository_SettleHold_Call) Run(run func(ctx context.Context, transferID uuid.UUID, operation string, accountRef string, amount decimal.Decimal, currency string)) *MoneyRepository_SettleHold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(decimal.Decimal), args[5].(string))
	})
	return _c
}

func (_c *MoneyRepository_SettleHold_Call) Return(_a0 interfaces.HoldResult, _a1 error) *MoneyRepository_SettleHold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MoneyRepository_SettleHold_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, decimal.Decimal, string) (interfaces.HoldResult, error)) *MoneyRepository_SettleHold_Call {
	_c.Call.Return(run)
	return _c
}

// NewMoneyRepository creates a new instance of MoneyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMoneyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MoneyRepository {
	mock := &MoneyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
