// Code generated by mockery. DO NOT EDIT.

package testmocks

import (
	context "context"
	entities "transx/internal/modules/wallet/domain/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OutboxRepository is an autogenerated mock type for the OutboxRepository type
type OutboxRepository struct {
	mock.Mock
}

type OutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OutboxRepository) EXPECT() *OutboxRepository_Expecter {
	return &OutboxRepository_Expecter{mock: &_m.Mock}
}

// ListPending provides a mock function with given fields: ctx, limit
func (_m *OutboxRepository) ListPending(ctx context.Context, limit int) ([]*entities.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []*entities.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*entities.OutboxEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*entities.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OutboxRepository_ListPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPending'
type OutboxRepository_ListPending_Call struct {
	*mock.Call
}

// ListPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *OutboxRepository_Expecter) ListPending(ctx interface{}, limit interface{}) *OutboxRepository_ListPending_Call {
	return &OutboxRepository_ListPending_Call{Call: _e.mock.On("ListPending", ctx, limit)}
}

func (_c *OutboxRepository_ListPending_Call) Run(run func(ctx context.Context, limit int)) *OutboxRepository_ListPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *OutboxRepository_ListPending_Call) Return(_a0 []*entities.OutboxEvent, _a1 error) *OutboxRepository_ListPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OutboxRepository_ListPending_Call) RunAndReturn(run func(context.Context, int) ([]*entities.OutboxEvent, error)) *OutboxRepository_ListPending_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function with given fields: ctx, id
func (_m *OutboxRepository) MarkPublished(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OutboxRepository_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type OutboxRepository_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *OutboxRepository_Expecter) MarkPublished(ctx interface{}, id interface{}) *OutboxRepository_MarkPublished_Call {
	return &OutboxRepository_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, id)}
}

func (_c *OutboxRepository_MarkPublished_Call) Run(run func(ctx context.Context, id uuid.UUID)) *OutboxRepository_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OutboxRepository_MarkPublished_Call) Return(_a0 error) *OutboxRepository_MarkPublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OutboxRepository_MarkPublished_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *OutboxRepository_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// NewOutboxRepository creates a new instance of OutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxRepository {
	mock := &OutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
