// Code generated by mockery. DO NOT EDIT.

package testmocks

import (
	context "context"
	entities "transx/internal/modules/wallet/domain/entities"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ProviderClient is an autogenerated mock type for the ProviderClient type
type ProviderClient struct {
	mock.Mock
}

type ProviderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ProviderClient) EXPECT() *ProviderClient_Expecter {
	return &ProviderClient_Expecter{mock: &_m.Mock}
}

// Submit provides a mock function with given fields: ctx, transferID, amount, currency
func (_m *ProviderClient) Submit(ctx context.Context, transferID uuid.UUID, amount decimal.Decimal, currency string) (entities.ProviderResult, error) {
	ret := _m.Called(ctx, transferID, amount, currency)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 entities.ProviderResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal, string) (entities.ProviderResult, error)); ok {
		return rf(ctx, transferID, amount, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal, string) entities.ProviderResult); ok {
		r0 = rf(ctx, transferID, amount, currency)
	} else {
		r0 = ret.Get(0).(entities.ProviderResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, decimal.Decimal, string) error); ok {
		r1 = rf(ctx, transferID, amount, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProviderClient_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type ProviderClient_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID uuid.UUID
//   - amount decimal.Decimal
//   - currency string
func (_e *ProviderClient_Expecter) Submit(ctx interface{}, transferID interface{}, amount interface{}, currency interface{}) *ProviderClient_Submit_Call {
	return &ProviderClient_Submit_Call{Call: _e.mock.On("Submit", ctx, transferID, amount, currency)}
}

func (_c *ProviderClient_Submit_Call) Run(run func(ctx context.Context, transferID uuid.UUID, amount decimal.Decimal, currency string)) *ProviderClient_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(decimal.Decimal), args[3].(string))
	})
	return _c
}

func (_c *ProviderClient_Submit_Call) Return(_a0 entities.ProviderResult, _a1 error) *ProviderClient_Submit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProviderClient_Submit_Call) RunAndReturn(run func(context.Context, uuid.UUID, decimal.Decimal, string) (entities.ProviderResult, error)) *ProviderClient_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// NewProviderClient creates a new instance of ProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProviderClient {
	mock := &ProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
