// Code generated by mockery. DO NOT EDIT.

package testmocks

import (
	context "context"
	interfaces "transx/internal/modules/auth/domain/interfaces"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RefreshSessionStore is an autogenerated mock type for the RefreshSessionStore type
type RefreshSessionStore struct {
	mock.Mock
}

type RefreshSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshSessionStore) EXPECT() *RefreshSessionStore_Expecter {
	return &RefreshSessionStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session, ttl
func (_m *RefreshSessionStore) Create(ctx context.Context, session interfaces.RefreshSession, ttl time.Duration) error {
	ret := _m.Called(ctx, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.RefreshSession, time.Duration) error); ok {
		r0 = rf(ctx, session, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshSessionStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RefreshSessionStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session interfaces.RefreshSession
//   - ttl time.Duration
func (_e *RefreshSessionStore_Expecter) Create(ctx interface{}, session interface{}, ttl interface{}) *RefreshSessionStore_Create_Call {
	return &RefreshSessionStore_Create_Call{Call: _e.mock.On("Create", ctx, session, ttl)}
}

func (_c *RefreshSessionStore_Create_Call) Run(run func(ctx context.Context, session interfaces.RefreshSession, ttl time.Duration)) *RefreshSessionStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.RefreshSession), args[2].(time.Duration))
	})
	return _c
}

func (_c *RefreshSessionStore_Create_Call) Return(_a0 error) *RefreshSessionStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshSessionStore_Create_Call) RunAndReturn(run func(context.Context, interfaces.RefreshSession, time.Duration) error) *RefreshSessionStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, sessionID
func (_m *RefreshSessionStore) Delete(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshSessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RefreshSessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *RefreshSessionStore_Expecter) Delete(ctx interface{}, sessionID interface{}) *RefreshSessionStore_Delete_Call {
	return &RefreshSessionStore_Delete_Call{Call: _e.mock.On("Delete", ctx, sessionID)}
}

func (_c *RefreshSessionStore_Delete_Call) Run(run func(ctx context.Context, sessionID string)) *RefreshSessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshSessionStore_Delete_Call) Return(_a0 error) *RefreshSessionStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshSessionStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *RefreshSessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, sessionID
func (_m *RefreshSessionStore) Get(ctx context.Context, sessionID string) (*interfaces.RefreshSession, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *interfaces.RefreshSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.RefreshSession, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.RefreshSession); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.RefreshSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RefreshSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *RefreshSessionStore_Expecter) Get(ctx interface{}, sessionID interface{}) *RefreshSessionStore_Get_Call {
	return &RefreshSessionStore_Get_Call{Call: _e.mock.On("Get", ctx, sessionID)}
}

func (_c *RefreshSessionStore_Get_Call) Run(run func(ctx context.Context, sessionID string)) *RefreshSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshSessionStore_Get_Call) Return(_a0 *interfaces.RefreshSession, _a1 error) *RefreshSessionStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshSessionStore_Get_Call) RunAndReturn(run func(context.Context, string) (*interfaces.RefreshSession, error)) *RefreshSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshSessionStore creates a new instance of RefreshSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshSessionStore {
	mock := &RefreshSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
