// Code generated by mockery. DO NOT EDIT.

package testmocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

type TokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenService) EXPECT() *TokenService_Expecter {
	return &TokenService_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: userID, now
func (_m *TokenService) Issue(userID uuid.UUID, now time.Time) (string, error) {
	ret := _m.Called(userID, now)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time) (string, error)); ok {
		return rf(userID, now)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time) string); ok {
		r0 = rf(userID, now)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time) error); ok {
		r1 = rf(userID, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenService_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenService_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - userID uuid.UUID
//   - now time.Time
func (_e *TokenService_Expecter) Issue(userID interface{}, now interface{}) *TokenService_Issue_Call {
	return &TokenService_Issue_Call{Call: _e.mock.On("Issue", userID, now)}
}

func (_c *TokenService_Issue_Call) Run(run func(userID uuid.UUID, now time.Time)) *TokenService_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(time.Time))
	})
	return _c
}

func (_c *TokenService_Issue_Call) Return(_a0 string, _a1 error) *TokenService_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenService_Issue_Call) RunAndReturn(run func(uuid.UUID, time.Time) (string, error)) *TokenService_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: tokenStr
func (_m *TokenService) Verify(tokenStr string) (uuid.UUID, error) {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type TokenService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - tokenStr string
func (_e *TokenService_Expecter) Verify(tokenStr interface{}) *TokenService_Verify_Call {
	return &TokenService_Verify_Call{Call: _e.mock.On("Verify", tokenStr)}
}

func (_c *TokenService_Verify_Call) Run(run func(tokenStr string)) *TokenService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenService_Verify_Call) Return(_a0 uuid.UUID, _a1 error) *TokenService_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenService_Verify_Call) RunAndReturn(run func(string) (uuid.UUID, error)) *TokenService_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenService creates a new instance of TokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
