// Code generated by mockery. DO NOT EDIT.

package testmocks

import (
	context "context"
	entities "transx/internal/modules/wallet/domain/entities"
	interfaces "transx/internal/modules/wallet/domain/interfaces"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TransferRepository is an autogenerated mock type for the TransferRepository type
type TransferRepository struct {
	mock.Mock
}

type TransferRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransferRepository) EXPECT() *TransferRepository_Expecter {
	return &TransferRepository_Expecter{mock: &_m.Mock}
}

// CountByUser provides a mock function with given fields: ctx, userID, status, accountRef
func (_m *TransferRepository) CountByUser(ctx context.Context, userID uuid.UUID, status *string, accountRef *string) (int64, error) {
	ret := _m.Called(ctx, userID, status, accountRef)

	if len(ret) == 0 {
		panic("no return value specified for CountByUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string) (int64, error)); ok {
		return rf(ctx, userID, status, accountRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string) int64); ok {
		r0 = rf(ctx, userID, status, accountRef)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, *string) error); ok {
		r1 = rf(ctx, userID, status, accountRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferRepository_CountByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUser'
type TransferRepository_CountByUser_Call struct {
	*mock.Call
}

// CountByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - status *string
//   - accountRef *string
func (_e *TransferRepository_Expecter) CountByUser(ctx interface{}, userID interface{}, status interface{}, accountRef interface{}) *TransferRepository_CountByUser_Call {
	return &TransferRepository_CountByUser_Call{Call: _e.mock.On("CountByUser", ctx, userID, status, accountRef)}
}

func (_c *TransferRepository_CountByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, status *string, accountRef *string)) *TransferRepository_CountByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *TransferRepository_CountByUser_Call) Return(_a0 int64, _a1 error) *TransferRepository_CountByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransferRepository_CountByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, *string, *string) (int64, error)) *TransferRepository_CountByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, t
func (_m *TransferRepository) Create(ctx context.Context, t *entities.Transfer) (*entities.Transfer, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Transfer) (*entities.Transfer, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Transfer) *entities.Transfer); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Transfer) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TransferRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *entities.Transfer
func (_e *TransferRepository_Expecter) Create(ctx interface{}, t interface{}) *TransferRepository_Create_Call {
	return &TransferRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *TransferRepository_Create_Call) Run(run func(ctx context.Context, t *entities.Transfer)) *TransferRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Transfer))
	})
	return _c
}

func (_c *TransferRepository_Create_Call) Return(_a0 *entities.Transfer, _a1 error) *TransferRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransferRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.Transfer) (*entities.Transfer, error)) *TransferRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteInternalTransfer provides a mock function with given fields: ctx, transferID, fx
func (_m *TransferRepository) ExecuteInternalTransfer(ctx context.Context, transferID uuid.UUID, fx interfaces.FXService) error {
	ret := _m.Called(ctx, transferID, fx)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteInternalTransfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, interfaces.FXService) error); ok {
		r0 = rf(ctx, transferID, fx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferRepository_ExecuteInternalTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteInternalTransfer'
type TransferRepository_ExecuteInternalTransfer_Call struct {
	*mock.Call
}

// ExecuteInternalTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID uuid.UUID
//   - fx interfaces.FXService
func (_e *TransferRepository_Expecter) ExecuteInternalTransfer(ctx interface{}, transferID interface{}, fx interface{}) *TransferRepository_ExecuteInternalTransfer_Call {
	return &TransferRepository_ExecuteInternalTransfer_Call{Call: _e.mock.On("ExecuteInternalTransfer", ctx, transferID, fx)}
}

func (_c *TransferRepository_ExecuteInternalTransfer_Call) Run(run func(ctx context.Context, transferID uuid.UUID, fx interfaces.FXService)) *TransferRepository_ExecuteInternalTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(interfaces.FXService))
	})
	return _c
}

func (_c *TransferRepository_ExecuteInternalTransfer_Call) Return(_a0 error) *TransferRepository_ExecuteInternalTransfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransferRepository_ExecuteInternalTransfer_Call) RunAndReturn(run func(context.Context, uuid.UUID, interfaces.FXService) error) *TransferRepository_ExecuteInternalTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserAndKey provides a mock function with given fields: ctx, userID, key
func (_m *TransferRepository) FindByUserAndKey(ctx context.Context, userID uuid.UUID, key string) (*entities.Transfer, error) {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndKey")
	}

	var r0 *entities.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entities.Transfer, error)); ok {
		return rf(ctx, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entities.Transfer); ok {
		r0 = rf(ctx, userID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferRepository_FindByUserAndKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndKey'
type TransferRepository_FindByUserAndKey_Call struct {
	*mock.Call
}

// FindByUserAndKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - key string
func (_e *TransferRepository_Expecter) FindByUserAndKey(ctx interface{}, userID interface{}, key interface{}) *TransferRepository_FindByUserAndKey_Call {
	return &TransferRepository_FindByUserAndKey_Call{Call: _e.mock.On("FindByUserAndKey", ctx, userID, key)}
}

func (_c *TransferRepository_FindByUserAndKey_Call) Run(run func(ctx context.Context, userID uuid.UUID, key string)) *TransferRepository_FindByUserAndKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *TransferRepository_FindByUserAndKey_Call) Return(_a0 *entities.Transfer, _a1 error) *TransferRepository_FindByUserAndKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransferRepository_FindByUserAndKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*entities.Transfer, error)) *TransferRepository_FindByUserAndKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TransferRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.Transfer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Transfer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TransferRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *TransferRepository_Expecter) GetByID(ctx interface{}, id interface{}) *TransferRepository_GetByID_Call {
	return &TransferRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TransferRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *TransferRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TransferRepository_GetByID_Call) Return(_a0 *entities.Transfer, _a1 error) *TransferRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransferRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entities.Transfer, error)) *TransferRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByReferenceForUser provides a mock function with given fields: ctx, reference, userID
func (_m *TransferRepository) GetByReferenceForUser(ctx context.Context, reference string, userID uuid.UUID) (*entities.Transfer, error) {
	ret := _m.Called(ctx, reference, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByReferenceForUser")
	}

	var r0 *entities.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*entities.Transfer, error)); ok {
		return rf(ctx, reference, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *entities.Transfer); ok {
		r0 = rf(ctx, reference, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, reference, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferRepository_GetByReferenceForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByReferenceForUser'
type TransferRepository_GetByReferenceForUser_Call struct {
	*mock.Call
}

// GetByReferenceForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - reference string
//   - userID uuid.UUID
func (_e *TransferRepository_Expecter) GetByReferenceForUser(ctx interface{}, reference interface{}, userID interface{}) *TransferRepository_GetByReferenceForUser_Call {
	return &TransferRepository_GetByReferenceForUser_Call{Call: _e.mock.On("GetByReferenceForUser", ctx, reference, userID)}
}

func (_c *TransferRepository_GetByReferenceForUser_Call) Run(run func(ctx context.Context, reference string, userID uuid.UUID)) *TransferRepository_GetByReferenceForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TransferRepository_GetByReferenceForUser_Call) Return(_a0 *entities.Transfer, _a1 error) *TransferRepository_GetByReferenceForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransferRepository_GetByReferenceForUser_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) (*entities.Transfer, error)) *TransferRepository_GetByReferenceForUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, status, accountRef, limit, offset
func (_m *TransferRepository) ListByUser(ctx context.Context, userID uuid.UUID, status *string, accountRef *string, limit int32, offset int32) ([]*entities.Transfer, error) {
	ret := _m.Called(ctx, userID, status, accountRef, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*entities.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, int32, int32) ([]*entities.Transfer, error)); ok {
		return rf(ctx, userID, status, accountRef, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, int32, int32) []*entities.Transfer); ok {
		r0 = rf(ctx, userID, status, accountRef, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, *string, int32, int32) error); ok {
		r1 = rf(ctx, userID, status, accountRef, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type TransferRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - status *string
//   - accountRef *string
//   - limit int32
//   - offset int32
func (_e *TransferRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, status interface{}, accountRef interface{}, limit interface{}, offset interface{}) *TransferRepository_ListByUser_Call {
	return &TransferRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, status, accountRef, limit, offset)}
}

func (_c *TransferRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, status *string, accountRef *string, limit int32, offset int32)) *TransferRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*string), args[3].(*string), args[4].(int32), args[5].(int32))
	})
	return _c
}

func (_c *TransferRepository_ListByUser_Call) Return(_a0 []*entities.Transfer, _a1 error) *TransferRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransferRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, *string, *string, int32, int32) ([]*entities.Transfer, error)) *TransferRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveExternalTransfer provides a mock function with given fields: ctx, transferID
func (_m *TransferRepository) ReserveExternalTransfer(ctx context.Context, transferID uuid.UUID) error {
	ret := _m.Called(ctx, transferID)

	if len(ret) == 0 {
		panic("no return value specified for ReserveExternalTransfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, transferID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferRepository_ReserveExternalTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveExternalTransfer'
type TransferRepository_ReserveExternalTransfer_Call struct {
	*mock.Call
}

// ReserveExternalTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID uuid.UUID
func (_e *TransferRepository_Expecter) ReserveExternalTransfer(ctx interface{}, transferID interface{}) *TransferRepository_ReserveExternalTransfer_Call {
	return &TransferRepository_ReserveExternalTransfer_Call{Call: _e.mock.On("ReserveExternalTransfer", ctx, transferID)}
}

func (_c *TransferRepository_ReserveExternalTransfer_Call) Run(run func(ctx context.Context, transferID uuid.UUID)) *TransferRepository_ReserveExternalTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TransferRepository_ReserveExternalTransfer_Call) Return(_a0 error) *TransferRepository_ReserveExternalTransfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransferRepository_ReserveExternalTransfer_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *TransferRepository_ReserveExternalTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// SettleExternalTransfer provides a mock function with given fields: ctx, transferID, result
func (_m *TransferRepository) SettleExternalTransfer(ctx context.Context, transferID uuid.UUID, result entities.ProviderResult) error {
	ret := _m.Called(ctx, transferID, result)

	if len(ret) == 0 {
		panic("no return value specified for SettleExternalTransfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entities.ProviderResult) error); ok {
		r0 = rf(ctx, transferID, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferRepository_SettleExternalTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SettleExternalTransfer'
type TransferRepository_SettleExternalTransfer_Call struct {
	*mock.Call
}

// SettleExternalTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID uuid.UUID
//   - result entities.ProviderResult
func (_e *TransferRepository_Expecter) SettleExternalTransfer(ctx interface{}, transferID interface{}, result interface{}) *TransferRepository_SettleExternalTransfer_Call {
	return &TransferRepository_SettleExternalTransfer_Call{Call: _e.mock.On("SettleExternalTransfer", ctx, transferID, result)}
}

func (_c *TransferRepository_SettleExternalTransfer_Call) Run(run func(ctx context.Context, transferID uuid.UUID, result entities.ProviderResult)) *TransferRepository_SettleExternalTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entities.ProviderResult))
	})
	return _c
}

func (_c *TransferRepository_SettleExternalTransfer_Call) Return(_a0 error) *TransferRepository_SettleExternalTransfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransferRepository_SettleExternalTransfer_Call) RunAndReturn(run func(context.Context, uuid.UUID, entities.ProviderResult) error) *TransferRepository_SettleExternalTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransferRepository creates a new instance of TransferRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransferRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransferRepository {
	mock := &TransferRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
